### ISSUE TITLE
Emphasise giving the list a name?

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/generic-scratch-make-list#16]
The ingredient **says** to give a new list a name, but the respective screenshot isn’t edited to draw attention to the name field, and in the whole ingredient the list in the screenshots is just “list name”.

**Comment by martinohanlon** [comment]
Updated generic-scratch3-make-list, this is the old Scratch 2 ingredient.

https://github.com/raspberrypilearning/generic-scratch3-make-list/pull/12

**Comment by martinohanlon** [comment]
Updated to include a highlight around the "list name", but also changed the list name to be "my list". Its more aligned to Scratch's way.

**Comment by martinohanlon** [comment]
resolved with https://github.com/raspberrypilearning/generic-scratch-make-list/pull/18
